accessible_schedule:
  description: 'Allow all employees read-only access to approved and scheduled jobs'
  type: 'boolean'
  default: false
use_connected_email:
  description: 'Send emails via connected Nylas account'
  type: 'boolean'
  default: true